remote_theme: hydecorp/hydejack@v9.1.6
plugins:
  - jekyll-include-cache

lang:                  en
title:                 Xin Tie

menu:
  - title:             Research
    url:               /research/
  - title:             Publications
    url:               /publications/
  - title:             Presentations
    url:               /presentations/
  - title:             CV
    url:               /CV/

