remote_theme: hydecorp/hydejack@v9.1.6
plugins:
  - jekyll-include-cache

menu:
  - title:             Research
    url:               /research/
  - title:             Publications
    url:               /publications/
  - title:             About
    url:               /about/

